include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Error
    always_use_package_imports: false
    # avoid_dynamic_calls: true
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    comment_references: true
    invariant_booleans: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_relative_imports: true
    test_types_in_equals: true
    # Style
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    # always_specify_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_field_initializers_in_const_classes: true
    # avoid_positional_boolean_parameters: true
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_void_async: true
    cascade_invocations: true
    conditional_uri_does_not_exist: true
    curly_braces_in_flow_control_structures: false
    deprecated_consistency: true
    directives_ordering: true
    eol_at_end_of_file: true
    file_names: false
    join_return_with_assignment: true
    library_names: false
    library_prefixes: false
    library_private_types_in_public_api: true
    missing_whitespace_between_adjacent_strings: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true
    only_throw_errors: true
    package_api_docs: true
    prefer_const_constructors: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    # prefer_final_parameters: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    # public_member_api_docs: true
    require_trailing_commas: true # experimental
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_colored_box: true # flutter
    use_decorated_box: true # flutter
    # use_enums: true # experimental
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true # experimental
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true # experimental
    # pub
    depend_on_referenced_packages: true
    secure_pubspec_urls: true
    sort_pub_dependencies: true
